(ns alura.start)
println "Ola nubankers"
(println "Ola")
(def total 150)
(println total)
(println "Total:" total)
(def total 566)
(println "Total:" total)
(+ 45 7)
(* 3 5)
(+ total 10)
(def total (+ total 100))
(println "Total:" total)
(println "Total:" total)
(def total (- total 100))
(println "Total:" total)
(def vetor [1, 4, 2])
(println "Vetor:" vetor)
vetor
(count vetor)
(conj vetor 89)
(pintln vetor)
(println vetor)
(def vetor (conj vetor 89))
(println vetor)
(defn imprime-msg []
         (println "Bem vindo(a) ao mundo clojete!"))
(imprime-msg)
(defn imprime-msg []
         (println "------------------------------")
         (println "Bem vindo(a) ao mundo clojure!")
         (println "------------------------------"))
(imprime-msg)
(defn discount [valor]
         (* valor 0.9))
(discount 100)
(discount 500)